# Generated by Django 2.2.3 on 2022-02-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='countrry',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='reference',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
