# Generated by Django 2.2.3 on 2022-03-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_addresses', '0002_auto_20220228_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Dirección de envío', 'verbose_name_plural': 'Dirección de envíos'},
        ),
    ]
