# Generated by Django 2.2.3 on 2022-03-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
    ]
